#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=48:00:00
#PBS -m ae
#PBS -M franpest@indiana.edu
#PBS -N 110411_CLASS_all_runs
#PBS -V
#PBS -o  /N/dc2/projects/lifebid/code/pestillilab_projects/precision_brain_science/s_classify_110411.out
#PBS -e  /N/dc2/projects/lifebid/code/pestillilab_projects/precision_brain_science/s_classify_110411.err

module load spm
module load matlab
cd /N/dc2/projects/lifebid/code/pestillilab_projects/precision_brain_science/

matlab -nojvm -nosplash -r s_classify_major_tracts_from_fe_structure_110411

