#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=48:00:00
#PBS -m ae
#PBS -M franpest@indiana.edu
#PBS -N Track_multiple_all_models_KK
#PBS -V
#PBS -o  /N/dc2/projects/lifebid/code/pestillilab_projects/precision_brain_science/s_track_multi_KK.out
#PBS -e  /N/dc2/projects/lifebid/code/pestillilab_projects/precision_brain_science/s_track_multi_kk.err

module load mrtrix/0.2

. /N/dc2/projects/lifebid/code/pestillilab_projects/et/mrtrix_ensemble.sh KK_96dirs_b2000_1p5iso
