#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=48:00:00
#PBS -m ae
#PBS -M franpest@indiana.edu
#PBS -N 113619_Track_multiple_all_models
#PBS -V
#PBS -o  /N/dc2/projects/lifebid/code/pestillilab_projects/precision_brain_science/s_track_multi_113619.out
#PBS -e  /N/dc2/projects/lifebid/code/pestillilab_projects/precision_brain_science/s_track_multi_113619.err

module load mrtrix/0.2

. /N/dc2/projects/lifebid/code/pestillilab_projects/et/mrtrix_ensemble.sh 113619
